name: Deploy rendered PDFs to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile all TeX files to PDF (recursive)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            **/*.tex
          work_in_root_file_dir: true
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1

      - name: Setup static-embedding-db
        uses: TCA166/static-embed-db@main # or @v1 after tagging
        with:
          tex_glob: '../*/*.tex'
          strip_paths: 1
          dist_dir: .

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: |
          mv index.html search.html
          pandoc README.md -o index.html --standalone

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload PDFs as artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
